GOVSP1515 - Disponibilização do conteúdo do despacho no acompanhamento do protocolo
projeto-siga/siga pull request #1590
Opened 2020-10-23 17:09 UTC by newtonyohei

A opção de disponibilizar na criação do despacho irá ser analisada pela equipe de requisitos porque no momento de criação o documento ainda não tem via e nem está juntado.
Na tela do dossiê (histórico) e de eventos do documento teremos o botão "Disponibilizar ao interessado" quando for juntado um despacho:

![image](https://user-images.githubusercontent.com/49542320/97032148-bb053f80-1537-11eb-96cc-41d49ccbff65.png)

Ao gerar o protocolo de acompanhamento aos usuários externos (botão "Gerar Protocolo", na tela do usuário será possível ver o conteúdo do despacho (primeiros 500 bytes) através de um tooltip:

![image](https://user-images.githubusercontent.com/49542320/97033180-53e88a80-1539-11eb-90c0-fe6bd958e331.png)

Criada movimentação "Disponibilizar ao interessado", que pode ser cancelada.

2020-10-23 18:45 UTC, Dinarde commented
Será revisada a implementação do REST

2020-10-28 18:53 UTC, Dinarde commented
Realizados os testes de segurança e implementação está adequada

2020-10-28 18:55 UTC, Dinarde requested changes
Aprovado nos quesitos de segurança do WS REST para obtenção do HTML

2020-10-28 18:56 UTC, Dinarde approved these changes

2020-10-30 14:33 UTC, merged

2020-10-30 14:43 UTC, newtonyohei commented
Alterado o nome da funcionalidade para "Disponibilizar no Acompanhamento do Protocolo" e foi incluído um checkbox possibilitando-a no momento da assinatura do documento.