Feature/gov/Resolvendo problema na alteração de registro de usuários
projeto-siga/siga pull request #2109
Opened 2022-05-25 19:56 UTC by gabrielfilipy

Pelo fato de ter uma CONSTRAINT na base de dados que garante que terá somente um usuário para um ORGAO/CARGO/FUNÇÃO DE CONFIANÇA/LOTAÇÃO e CPF. Logo, quando existe dois usuários com os mesmos registros sendo que um deles está INATIVO é lançado uma exceção (ConstraintViolationException) impossibilitando tal alteração.

Analisando o código pude perceber em um dos métodos responsável por essa rotina estava chamando um outro método que trás uma coleção de usuários com CPF ativos e inativos, por esse motivo estava impossibilitando a alteração. Daí substituí por um método já existente no sistema que trás somente os CPF ativos. Em tese, agora é possível alterar registro de usuário ativo que possui o mesmo registro de outro usuário inativo.

Evidência: 
![alter](https://user-images.githubusercontent.com/73559672/170355670-cb02c48c-0d02-4d53-938c-85d3464375a7.jpg)

![result](https://user-images.githubusercontent.com/73559672/170355705-412d4670-50ef-48a2-9c79-50f31b915e71.jpg)

2022-05-26 18:49 UTC, dinarde requested changes
Há um erro nessa análise. 

A verificação dos CPFs iguais é feita no bloco anterior com a query consultarQuantidade.
A lista "listaPessoasMesmoCPF" é usada para outro fim que analisando superficialmente é para propagar a alteração do NOME em todos os registros (Inativos ou não) daquele CPF.

Sugiro que analise o PR1699, pois para mim o problema está na propagação da DATA_FIM para um novo registro:

	**pessoa2.setDataFimPessoa(data);**
					
	........

	**pessoa2.setDataFimPessoa(dpPessoaAnt2.getDataFimPessoa());**

Se você olhar no For Each dessa lista há dois SETs na data fim. O segundo SET viola a sua constraint criada: **user_index_for_un** e **siga_valid_unique**. 

Não fica muito claro o uso da DATA_FIM_PESSOA como atributo único. Como esse dado é copiado aí no FOR, viola pois tem dois DATA_FIM iguais para os msms IDs + CPF. Para esses casos talvez o mais recomendado fosse usar o CASE WHEN:

CASE  WHEN "DATA_FIM_PESSOA" IS NULL THEN "ID_ORGAO_USU, ID_CARGO, ID_FUNCAO_CONFIANCA, ID_LOTACAO, CPF_PESSOA" END 

A troca feita funciona pq vc tira da lista essa cópia de registros com data fim.
Sugiro revisar isso. Pois a implementação fará a não propagação da alteração de NOME conforme o que foi feito no PR citado.

2022-05-30 13:16 UTC, gabrielfilipy commented
Olá, tudo bem? Grato pela observação, Dinarde. Duas perguntas:
1 - Usar esse CASE WHEN no consultarPorCpfAtivoInativo?
2 - Se sim, como incluir isso nessa query consultarPorCpfAtivoInativo, pois
humildemente reconheço que eu nunca utilizei isso em jpql tampouco em hql,
e já pesquisei e não tive êxito. Se puder me me dar um norte agradeço.

Em qui., 26 de mai. de 2022 às 15:50, dinarde ***@***.***>
escreveu:

> ***@***.**** requested changes on this pull request.
>
> Há um erro nessa análise.
>
> A verificação dos CPFs iguais é feita no bloco anterior com a query
> consultarQuantidade.
> A lista "listaPessoasMesmoCPF" é usada para outro fim que analisando
> superficialmente é para propagar a alteração do NOME em todos os registros
> (Inativos ou não) daquele CPF.
>
> Sugiro que analise o PR1699, pois para mim o problema está na propagação
> da DATA_FIM para um novo registro:
>
> **pessoa2.setDataFimPessoa(data);**
>
> 				
>
> ........
>
>
>
> **pessoa2.setDataFimPessoa(dpPessoaAnt2.getDataFimPessoa());**
>
>
> Se você olhar no For Each dessa lista há dois SETs na data fim. O segundo
> SET viola a sua constraint criada: *user_index_for_un* e
> *siga_valid_unique*.
>
> Não fica muito claro o uso da DATA_FIM_PESSOA como atributo único. Como
> esse dado é copiado aí no FOR, viola pois tem dois DATA_FIM iguais para os
> msms IDs + CPF. Para esses casos talvez o mais recomendado fosse usar o
> CASE WHEN:
>
> CASE WHEN "DATA_FIM_PESSOA" IS NULL THEN "ID_ORGAO_USU, ID_CARGO,
> ID_FUNCAO_CONFIANCA, ID_LOTACAO, CPF_PESSOA" END
>
> A troca feita funciona pq vc tira da lista essa cópia de registros com
> data fim.
> Sugiro revisar isso. Pois a implementação fará a não propagação da
> alteração de NOME conforme o que foi feito no PR citado.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/projeto-siga/siga/pull/2109#pullrequestreview-986647846>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARRG46C3QO7KL3J337GAANDVL7BV5ANCNFSM5W6JRG6Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-05-31 12:27 UTC, dinarde commented
> CASE WHEN

O CASE WHEN deveria estar no índice e na Constraint do Script V116:

-- -----------------------------------------------------------------------------------------------
--	SCRIPT: EVITA A DUPLICIDADE DE PESSOAS COM O MESMO Órgão, Cargo, Função, Unidade e CPF.
-- -----------------------------------------------------------------------------------------------
CREATE INDEX user_index_for_un ON CORPORATIVO.DP_PESSOA (ID_ORGAO_USU, ID_CARGO, ID_FUNCAO_CONFIANCA, ID_LOTACAO, CPF_PESSOA, **DATA_FIM_PESSOA**);
alter table CORPORATIVO.DP_PESSOA add constraint siga_valid_unique unique (ID_ORGAO_USU, ID_CARGO, ID_FUNCAO_CONFIANCA, ID_LOTACAO, CPF_PESSOA, **DATA_FIM_PESSOA**) ENABLE NOVALIDATE;


Essa DATA_FIM_PESSOA com essa funcionalidade de propagação de alteração de NOME em registros ATIVOS e INATIVOS viola essa constraint que você criou.

![image](https://user-images.githubusercontent.com/20362170/171171556-886b6424-9b7f-499c-bcf1-0bb806c1ecf1.png)

Nesse FOR quando vc tem o CPF 111.111.111-11 com o nome Jose da Silva e você altera para o CPF 111.111.111-11 o nome Jos**é** da Silva ele irá pegar todo mundo desse CPF **listaPessoasMesmoCPF** e aplicar a alteração.

Se você retirar os INATIVOS conforme foi feito, esses registros ficaram sem a correção do nome e numa futura ativação o NOME vai ficar divergente.

Então sugiro avaliar colocar na Constraint o CASE WHEN DATA_FIM_PESSOA IS NULL ou seja CASO a DATA_FIM_PESSOA seja NULL verifique se ID_ORGAO_USU, ID_CARGO, ID_FUNCAO_CONFIANCA, ID_LOTACAO, CPF_PESSOA é UNICO.
Assim como é feito com outras Constraint. Por Ex Script 77.:

CREATE UNIQUE INDEX corporativo.dp_pessoa_unique_pessoa_ativa on CORPORATIVO.DP_PESSOA (**CASE WHEN DATA_FIM_PESSOA IS NULL THEN** ID_PESSOA_INICIAL END);


A restrição é que isso só funciona para ORACLE. Há a pendência de achar uma solução para MySQL em todas as CONSTRAINT que utilizam o CASE WHEN, mas não é o escopo dessa correção.

2022-05-31 12:36 UTC, dinarde commented
A correção referente a violação dessa constraint ela tange apenas a alteração do INDEX e da CONSTRAINT. Não necessitaria alterar o código.

2022-06-15 12:07 UTC, dinarde commented
Encerrado por inatividade. Favor reabrir o PR com as correções solicitadas

2022-06-15 12:07 UTC, closed without merging