Feature/govsp/rm141262 transfere docs arquivados
projeto-siga/siga pull request #2298
Opened 2023-02-15 13:59 UTC by NatanaeLuiz

**Implementação da funcionalidade de transferir documentos arquivados em lote.**

Este pull request visa implementar a função de transferência de documentos arquivados 

- Foi adicionado uma permissão para liberar acesso a tela de transferência. (A permissão de “Transferência de Documentos” será atribuída pelo administrador do sistema ao administrador local do órgão)
![image](https://user-images.githubusercontent.com/17768272/219035687-d0b67f43-e34e-4b75-b6af-fb07bde6e50e.png)

- Foi criado uma nova tela para realizar a ação de transferir documentos arquivados de uma ORIGEM para um DESTINO.

![image](https://user-images.githubusercontent.com/17768272/219046946-44949d33-8c7b-4626-be09-216dbe17d9f7.png)

- Ao selecionar o botão PESQUISAR passando uma UNIDADE ou USUARIO como ORIGEM o sistema realiza uma busca para retornar os documentos relacionados aquela UNIDADE ou USUARIO, os documentos retornados são do tipo:

1 - Arquivado Corrente
2 - Arquivado Intermediário
3 - Arquivado Permanente

![image](https://user-images.githubusercontent.com/17768272/219034812-ec9d5b84-1040-4a71-abba-579bd044ea62.png)

- Antes de transferir o usuário deve informar um DESTINO e um MOTIVO para transferência.
- Foi Adicionado um popup para confirmação da transferência:

![image](https://user-images.githubusercontent.com/17768272/219037972-c8c23879-00bb-4583-b8bc-43477ee489f3.png)

- Histórico de Movimentações após a transferência:

![image](https://user-images.githubusercontent.com/17768272/219043962-e1c8a303-e202-4ad4-a7f7-0b2828e5ef5a.png)

Por fim o documento e recebido na mesma mesa (mesa **OUTROS** para documentos arquivados) da unidade informada como DESTINO.

OBS: A nova movimentação criada como arquivamento está ficando com a coloração CINZA como se tivesse invalida, pois está com uma idMovRef apontando para uma movimentação de cancelamento. o mesmo deve ser tratado em um RM separadamente desse RM de transferência de documentos arquivados.

2023-02-28 12:47 UTC, crivano requested changes

2023-03-01 13:58 UTC, NatanaeLuiz commented on siga-ex/src/main/java/br/gov/jfrj/siga/ex/AbstractExDocumento.java
> +				+ "                and (marca.cpMarcador.idMarcador=6 or marca.cpMarcador.idMarcador=12 or marca.cpMarcador.idMarcador=13)"
Corrigido

2023-03-01 13:59 UTC, NatanaeLuiz commented on siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
> +	public void reestruturacaoDocsArquivado(ExMobil mob, List<ExMovimentacao> movs, DpPessoa cadastrante, final DpLotacao lotaCadastrante,
Corrigido

2023-03-01 13:59 UTC, NatanaeLuiz commented on siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
> +			movArquivamentoNova = criarNovaMovimentacao(ExTipoDeMovimentacao.ARQUIVAMENTO_CORRENTE, cadastrante,
Corrigido

2023-03-01 13:59 UTC, NatanaeLuiz commented on siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExMarcadorBL.java
> +		if (mov.getExMovimentacaoRef() != null && mov.getExMovimentacaoRef().getExTipoMovimentacao() == ExTipoDeMovimentacao.ARQUIVAMENTO_CORRENTE)
Corrigido

2023-03-01 14:00 UTC, NatanaeLuiz commented on siga-ex/src/main/java/br/gov/jfrj/siga/ex/vo/ExMovimentacaoVO.java
> +		if(mov.getExMovimentacaoCanceladora() != null && mov.getExTipoMovimentacao() == ExTipoDeMovimentacao.ARQUIVAMENTO_CORRENTE)
Corrigido

2023-03-01 14:00 UTC, NatanaeLuiz commented on siga-ex/src/main/java/br/gov/jfrj/siga/ex/vo/ExMovimentacaoVO.java
> +		desabilitada = (mov.getExMovimentacaoRef() != null && mov.getExMovimentacaoRef().isCancelada() && mov.getExTipoMovimentacao() != (ExTipoDeMovimentacao.MARCACAO) && mov.getExTipoMovimentacao() != (E
Corrigido

2023-03-01 14:01 UTC, NatanaeLuiz commented on siga-ex/src/main/java/br/gov/jfrj/siga/hibernate/ExDao.java
> +	public List<ExDocumento> consultarArquivadosParaTransferirEmLote(Long idPessoa, Long idLotacao, Integer offset, Integer tamPagina) {
Corrigido

2023-03-01 14:03 UTC, NatanaeLuiz commented on sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
> +	public void aTransferirDocArquivadoLote(Integer paramoffset, final DpPessoaSelecao responsavelSel, final DpLotacaoSelecao lotaResponsavelSel, final DpLotacaoSelecao lotacaoDestinatarioSel,
Corrigido

2023-03-01 14:03 UTC, NatanaeLuiz commented on sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
> +	protected Map<Integer, String> getListaTipoRespPerfilOrigem() {
Corrigido

2023-03-01 14:04 UTC, NatanaeLuiz commented on sigaex/src/main/webapp/WEB-INF/page/exPainel/exibe.jsp
> +										<c:when test="${mov.exTipoMovimentacao == 'ARQUIVAMENTO_CORRENTE'}">
Corrigido

2023-03-01 14:04 UTC, NatanaeLuiz commented on sigaex/src/main/webapp/paginas/menus/menu.jsp
> +								href="/sigaex/app/expediente/mov/transferir_doc_arquivado_lote">Transferência</a>
Corrigido

2023-03-01 17:40 UTC, NatanaeLuiz commented on sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
> +	public void aTransferirLoteDocArquivado(
Foi criado o RM #155730 - Retactor Transferencia Documentos, para tratar dessa melhoria separadamente

2023-03-01 21:11 UTC, dinarde requested changes
Favor verificar os apontamentos e caso não tem alterações avisar para realizar a aprovação

2023-03-01 21:11 UTC, dinarde commented on sigaex/src/main/webapp/WEB-INF/page/exDocumento/aExibirHistorico.jsp
> +													<c:set var="acaourl" value="${acao.url}"/>
Acredito que isso deve quebrar a exibição do protocolo do arquivamento. Teria que tratar aqui ou na origem no VO

2023-03-01 21:11 UTC, dinarde commented on sigaex/src/main/webapp/WEB-INF/page/exDocumento/aExibirHistorico.jsp
> +													<c:set var="acaourl" value="${acao.url}"/>
![image](https://user-images.githubusercontent.com/20362170/222265169-d1b3db2f-8771-4534-a757-74aa64eee914.png)
verificar se continua com o contexto após a alteração

2023-03-02 13:30 UTC, NatanaeLuiz commented on sigaex/src/main/webapp/WEB-INF/page/exDocumento/aExibirHistorico.jsp
> +													<c:set var="acaourl" value="${acao.url}"/>
Corrigido

2023-03-02 13:30 UTC, NatanaeLuiz commented on siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
> +			movArquivadaACancelar.setDescrMov(descrMov);
Corrigido

2023-03-02 13:31 UTC, NatanaeLuiz commented on siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
> +	 * Cancela um documento de ORIGEM que esteja arquivado e arquiva novamente na Lotação de DESTINO sem mudar
Corrigido

2023-03-02 13:55 UTC, NatanaeLuiz commented on sigaex/src/main/webapp/WEB-INF/page/exDocumento/aExibirHistorico.jsp
> +									<td class="text-center ${mov.disabled}">
Corrigido

2023-03-03 17:15 UTC, merged

2023-03-03 17:15 UTC, dinarde commented
Falta converter para XHR e capturar o erro lançado pela BL